cbmem: Fix dependency generation
CPPFLAGS was split off, but not taken into regard in dependency
generation. Somewhat cosmetic.

BUG=chrome-os-partner:18638
TEST=emerge-stout32 chromeos-coreboot-stout32 shows no
     cbmem.c:36:34: fatal error: boot/coreboot_tables.h: No such file or directory
     anymore.
Signed-off-by: Stefan Reinauer <reinauer@google.com>

Change-Id: Ia9d2e10a3ef122f30d681d16c2291eb108ead835
Reviewed-on: https://gerrit.chromium.org/gerrit/48322
Reviewed-by: David James <davidjames@chromium.org>
Commit-Queue: Stefan Reinauer <reinauer@google.com>
Tested-by: Stefan Reinauer <reinauer@google.com>